export default {
  extends: ["stylelint-config-standard"],
  ignoreFiles: [
    "**/.next/**",
    "**/node_modules/**",
    "**/storybook-static/**",
    "**/coverage/**",
    "**/out/**",
    "**/dist/**",
  ],
  rules: {
    "alpha-value-notation": null,
    "at-rule-empty-line-before": null,
    "at-rule-no-unknown": [
      true,
      {
        ignoreAtRules: [
          "theme",
          "source",
          "plugin",
          "utility",
          "custom-variant",
          "variant",
          "apply",
          "reference",
          "tailwind",
          "config",
          "page",
          "bottom-left",
          "bottom-right",
        ],
      },
    ],
    "color-function-alias-notation": null,
    "color-function-notation": null,
    "comment-empty-line-before": null,
    "custom-property-empty-line-before": null,
    "custom-property-pattern": null,
    "declaration-empty-line-before": null,
    "import-notation": null,
    "keyframe-selector-notation": null,
    "media-feature-range-notation": null,
    "nesting-selector-no-missing-scoping-root": null,
    "rule-empty-line-before": null,
    "value-keyword-case": null,
  },
}